# Generated by Django 4.0.6 on 2022-07-29 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('amount_paid', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=200)),
                ('order_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
    ]
